{% set name = "aubio" %}
{% set version = "0.4.9" %}
{% set sha256 = "d48282ae4dab83b3dc94c16cf011bcb63835c1c02b515490e1883049c3d1f3da" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://aubio.org/pub/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 9
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vvv"

requirements:
  build:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - numpy
    - ffmpeg
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - aubio

about:
  home: https://aubio.org
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'tools for audio and music analysis and transformation'
  description: |
    aubio provides a set of tools for analysis and transformation of sounds.
    Numpy arrays are used to store vectors and matrices, while computations
    are done in C, for speed and memory efficiency.
  doc_url: https://aubio.org/manual/latest
  dev_url: https://github.com/aubio/aubio/

extra:
  recipe-maintainers:
    - piem
    - MartinHN
