appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: h1HVRGtkxi/IOs+XRDqEqQ/6TYXThBBdFfF1dJvvD3LdhBXHpqJxV0LQFresOMBjsP85TI5CL0Dn8/Hw5Z+aGEBKvAs/dZPxd3hGda9Y6nGvweQPZrdZA+b8ubZpGNvLhdbWn5Q2zWFWmOUhBWwY/rdXviup3mmd07seAaOHs/YzGnCqPIlS8sgyM6VfPQdx51s9nZ0J27vfr7ELK1v+cbvYOayFA3OMwXYfo9xqqiMwKeEWmwN2t5TkXSBjhtLTbCe+tm4ClIg4q6aZnzLS4MbBkELIRpUtf+O9Qbg+AcwFJXX//Ea03Ezgafh5jzAiyqZ/eG30PkarRiLDtka+ofVmhBehi/5l2WuSOPVpH/oJ3rU2MdHohAV+YoPH5I/ycYTmryoVEEXWh+ZnB5zvKp6KWx0sMObhofj2L4nHVgFMchRv5MVMxNiC9b1gbTKGuKh9POZER7fS5zT7PVG0WF3w1nXLe4SUNOqPbf45MghLQHVYVDdHB0MwJYLlsfsq2cBtfL/4THoGAsfi0k8+0PinuyVSWu9EQ7UWhH46EzkYy59ZoFDlPH7rp0suanyu3vAS7mHP3ZC1N7L0Img1G3yXDl14Nc/ut/D3ThpxzPoUAP3LwMLqBb9TwZMfAmTut/2ly14jaJjAMGFZwJF6tsJV68BJs4J4Sj7v7LXOcW4=}
provider:
  win: azure
conda_forge_output_validation: false
